import Head from 'next/head';
import Link from 'next/link';


export default function Home() {
  return (
    <div>
      <Head>
        <title>PayQart Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <div className="container pt-5">
            <h2 className="text-center">PayQart Frontend Assessment</h2>
            <div className="row __center__div">
              <div className="col-md-5">
             
                <div className="card ">
                  <div className="card-body">
                  <h5 className="card-title">Frontend Task</h5>
                    <p className="card-text">Reproduce the mockup and connect the api as instructed</p>
                     <Link href="/order">
                        <a className="btn btn-primary text-white">Preview</a>
                     </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </>
    </div>
  )
}
